# Tensors

* A torch is a multi-dim matrix containing elements of a single data type.
* Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's)
* default datatype of float32.
* More suitable for DL then a numpy array

In [3]:
import torch
import numpy as np

# Lists

In [4]:
my_list = [[1, 2], [3, 4]]
my_list

[[1, 2], [3, 4]]

# Numpy Array

In [5]:
np1 = np.random.rand(4, 4)
np1

array([[0.84781136, 0.45356856, 0.523766  , 0.95784514],
       [0.64705596, 0.04795623, 0.35464058, 0.15836711],
       [0.57947308, 0.65852217, 0.76176591, 0.75470592],
       [0.10588328, 0.30143238, 0.8054492 , 0.85267795]])

In [6]:
np1.dtype

dtype('float64')

# Tensors

In [7]:
tensor_2d = torch.randn(4, 4)
tensor_2d

tensor([[-1.0463,  0.0686, -0.5600,  0.4913],
        [-1.0882,  0.2772, -0.6668,  0.5364],
        [-1.3718,  0.7793, -1.8330,  2.1230],
        [ 0.5056,  0.5010, -0.5769, -0.2931]])

In [8]:
tensor_3d = torch.randn(2, 3, 4)
tensor_3d

tensor([[[-0.6727,  0.2149,  0.5973, -1.5539],
         [-0.7421, -1.3391, -0.3470, -1.6300],
         [-0.0918, -1.4990,  1.1055, -1.3470]],

        [[-0.7453, -0.2594,  1.7996, -0.6395],
         [-0.3538,  0.1932, -1.6250,  0.2811],
         [ 0.0965, -0.2910,  0.8324,  0.4731]]])

In [12]:
tensor_3d.dtype

torch.float32

In [9]:
#creating a tensor from a numpy array
np_tensor = torch.from_numpy(np1)

In [10]:
np_tensor

tensor([[0.8478, 0.4536, 0.5238, 0.9578],
        [0.6471, 0.0480, 0.3546, 0.1584],
        [0.5795, 0.6585, 0.7618, 0.7547],
        [0.1059, 0.3014, 0.8054, 0.8527]], dtype=torch.float64)