In [1]:
import torch

In [2]:
my_torch = torch.arange(12)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
#reshape and views
my_torch = my_torch.reshape(3,4)
my_torch

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [4]:
# reshape if we dont know the number of items using -1
my_torch1 = torch.arange(12)
my_torch1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
my_torch1 = my_torch1.reshape(2,-1)

In [8]:
my_torch1

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [9]:
my_torch2 = my_torch1.view(3,4)
my_torch2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
#if we change the a item in the parent tensor, the child tensor will also change (it will updated)

In [12]:
# Slices
my_torch0 = torch.arange(12)

In [13]:
my_torch0[4]

tensor(4)

In [14]:
#grabbing a range
mat = my_torch0.reshape(3,4)

In [16]:
mat

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [18]:
mat[0,:]

tensor([0, 1, 2, 3])

# Tensor Math Op

* add,sub,mul,div,mod,exp
* shortland and uh, longland
* Reassignment

In [20]:
import torch
import numpy as np

In [22]:

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
 

In [23]:
#add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [24]:
#add longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
#sub
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [26]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [27]:
#mul
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [28]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [29]:
#divide
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [30]:
# div longhand
torch.div(tensor_a, tensor_b)


tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [32]:
# remider
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [33]:
#remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [34]:
#epxonential / power
tensor_a ** 2

tensor([ 1,  4,  9, 16])

In [35]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [36]:
tensor_b.add(tensor_a)

tensor([ 6,  8, 10, 12])

In [37]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [38]:
tensor_a

tensor([ 6,  8, 10, 12])